import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Download, Plus, Save, Trash2 } from "lucide-react";

import { addFilmTimelineClip, moveFilmTimelineClip, removeFilmTimelineClip, updateFilmTimelineClip, validateFilmTimelineDraft } from "@/lib/film-timeline";
import { filmDeliverableDownloadURL, type FilmStatus } from "@/services/film-client";
import type { FilmTimeline, FilmTimelineClip, FilmTrackKind } from "@/types/film";
import { WorkbenchSection } from "./WorkbenchSection";

const trackLabels: Record<FilmTrackKind, string> = { video: "视频", dialogue: "对白", music: "音乐", sfx: "音效", subtitle: "字幕" };

export function TimelinePanel({ timeline, dirty, busy, onChange, onSave }: { timeline: FilmTimeline; dirty: boolean; busy: boolean; onChange: (timeline: FilmTimeline) => void; onSave: () => void }) {
  const errors = useMemo(() => validateFilmTimelineDraft(timeline), [timeline]);
  const addClip = (trackId: string, kind: FilmTrackKind) => onChange(addFilmTimelineClip(timeline, trackId, { source: kind === "subtitle" ? "manual" : `${kind}-source`, start: 0, end: 2, ...(kind === "subtitle" ? { text: "Subtitle" } : {}) }));
  return <WorkbenchSection id="timeline" title="多轨时间线 / Timeline" wide>
    <div className="grid gap-3 sm:grid-cols-3"><NumberField label="宽度" value={timeline.width} onChange={(width) => onChange({ ...timeline, width })} /><NumberField label="高度" value={timeline.height} onChange={(height) => onChange({ ...timeline, height })} /><NumberField label="帧率" value={timeline.frameRate} onChange={(frameRate) => onChange({ ...timeline, frameRate })} /></div>
    <div className="mt-4 space-y-3">{timeline.tracks.map((track) => <div key={track.id} data-testid={`timeline-track-${track.kind}`} className="rounded-xl border border-[var(--ob-line)] p-3"><div className="flex items-center"><strong className="mr-auto text-sm">{trackLabels[track.kind]} · {track.title}</strong><button className="ob-btn" aria-label={`添加 ${track.kind} 片段`} onClick={() => addClip(track.id, track.kind)}><Plus size={14} /> 添加片段</button></div><div className="mt-2 space-y-2">{[...track.clips].sort((a, b) => a.order - b.order).map((clip) => <ClipEditor key={clip.id} clip={clip} subtitle={track.kind === "subtitle"} onPatch={(patch) => onChange(updateFilmTimelineClip(timeline, track.id, clip.id, patch))} onMove={(offset) => onChange(moveFilmTimelineClip(timeline, track.id, clip.id, offset))} onRemove={() => onChange(removeFilmTimelineClip(timeline, track.id, clip.id))} />)}</div></div>)}</div>
    {errors.length ? <div role="alert" className="ob-banner mt-3" data-tone="danger"><ul className="list-disc pl-4 text-sm">{errors.slice(0, 8).map((error) => <li key={error}>{error}</li>)}</ul></div> : null}
    <div className="mt-3 flex items-center gap-2"><button type="button" className="ob-btn ob-btn-primary" disabled={busy || !dirty || errors.length > 0} onClick={onSave}><Save size={14} /> 保存时间线</button><span className="text-xs text-[var(--ob-muted)]">{dirty ? "有未保存修改" : "已与服务端同步"}</span></div>
  </WorkbenchSection>;
}

function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs">{label}<input className="ob-input mt-1 w-full" type="number" value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }

function ClipEditor({ clip, subtitle, onPatch, onMove, onRemove }: { clip: FilmTimelineClip; subtitle: boolean; onPatch: (patch: Partial<FilmTimelineClip>) => void; onMove: (offset: -1 | 1) => void; onRemove: () => void }) {
  return <div data-testid="timeline-clip" className="rounded-lg bg-[var(--ob-canvas)] p-2"><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-8"><label className="text-xs">素材<input aria-label="素材" className="ob-input mt-1 w-full" value={clip.source} onChange={(event) => onPatch({ source: event.target.value })} /></label><NumberField label="入点" value={clip.start} onChange={(start) => onPatch({ start })} /><NumberField label="出点" value={clip.end} onChange={(end) => onPatch({ end })} /><NumberField label="素材 in" value={clip.trimIn} onChange={(trimIn) => onPatch({ trimIn })} /><NumberField label="素材 out" value={clip.trimOut} onChange={(trimOut) => onPatch({ trimOut })} /><NumberField label="音量" value={clip.volume} onChange={(volume) => onPatch({ volume })} /><NumberField label="淡入" value={clip.fadeIn} onChange={(fadeIn) => onPatch({ fadeIn })} /><NumberField label="淡出" value={clip.fadeOut} onChange={(fadeOut) => onPatch({ fadeOut })} /></div>{subtitle ? <input aria-label="字幕文本" className="ob-input mt-2 w-full" value={clip.text ?? ""} onChange={(event) => onPatch({ text: event.target.value })} /> : null}<div className="mt-2 flex flex-wrap gap-2"><label className="text-xs"><input type="checkbox" checked={clip.muted} onChange={(event) => onPatch({ muted: event.target.checked })} /> 静音</label><select aria-label="转场" className="ob-input py-1 text-xs" value={clip.transition} onChange={(event) => onPatch({ transition: event.target.value as "cut" | "fade" })}><option value="cut">cut</option><option value="fade">fade</option></select><button className="ob-btn" aria-label="片段上移" onClick={() => onMove(-1)}><ArrowUp size={13} /></button><button className="ob-btn" aria-label="片段下移" onClick={() => onMove(1)}><ArrowDown size={13} /></button><button className="ob-btn" aria-label="删除片段" onClick={onRemove}><Trash2 size={13} /></button></div></div>;
}

export function DeliveryPanel({ status, busy, onExport, onRefresh }: { status: FilmStatus; busy: boolean; onExport: (kind: "mp4" | "srt" | "manifest" | "asset_bundle") => void; onRefresh: () => void }) {
  const [kind, setKind] = useState<"mp4" | "srt" | "manifest" | "asset_bundle">("manifest");
  const disabled = (kind === "mp4" && !status.capabilities.mp4Export) || (kind === "asset_bundle" && !status.capabilities.assetBundleExport);
  return <WorkbenchSection id="delivery" title="异步交付 / Delivery">
    <div className="flex flex-wrap gap-2"><select aria-label="导出类型" className="ob-input" value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="mp4" disabled={!status.capabilities.mp4Export}>MP4</option><option value="srt">SRT</option><option value="manifest">manifest</option><option value="asset_bundle" disabled={!status.capabilities.assetBundleExport}>asset_bundle</option></select><button className="ob-btn ob-btn-primary" disabled={busy || disabled} onClick={() => onExport(kind)}>请求导出</button><button className="ob-btn" onClick={onRefresh}>刷新状态</button></div>
    {!status.capabilities.mp4Export ? <p className="mt-2 text-xs text-[var(--ob-danger)]">MP4 不可用：{status.capabilities.mp4Diagnostic}</p> : null}{!status.capabilities.assetBundleExport ? <p className="mt-1 text-xs text-[var(--ob-muted)]">asset_bundle 未由当前后端启用。</p> : null}
    <ul className="mt-4 space-y-2">{status.document.deliverables.map((item) => <li key={item.id} className="rounded-lg border border-[var(--ob-line)] p-3"><div className="flex items-center gap-2"><strong className="mr-auto text-sm">{item.title}</strong><span className="text-xs">{item.kind} · {item.status}</span></div>{item.diagnostic ? <p className="text-xs text-[var(--ob-danger)]">{item.diagnostic}</p> : null}{item.status === "approved" && (item.storageKey || item.content) ? <a className="ob-btn mt-2 inline-flex" href={filmDeliverableDownloadURL(status.document.projectId, item.id)}><Download size={14} /> 下载</a> : null}</li>)}</ul>
  </WorkbenchSection>;
}
