export const filmZhCN = {
  "film.nav.manuscript": "原稿", "film.nav.decomposition": "AI 拆解", "film.nav.script": "AI 剧本", "film.nav.styles": "风格模板", "film.nav.assets": "资产", "film.nav.episodes": "分集制作", "film.nav.tasks": "任务", "film.nav.projection": "投影", "film.nav.timeline": "时间线", "film.nav.quality": "质量", "film.nav.delivery": "交付", "film.nav.agent": "Agent",
  "film.quality.title": "质量检查", "film.quality.run": "运行检查", "film.quality.summary": "{issues} 个问题，{repairs} 个修复建议", "film.quality.impact": "影响 {targets} 项 · 预计 {generations} 次生成", "film.quality.applied": "已应用", "film.quality.configureApprove": "配置并批准", "film.quality.approveApply": "批准并应用", "film.quality.repairModel": "修复生成模型", "film.quality.noModel": "没有支持此修复阶段的模型", "film.quality.loadingCatalog": "正在加载能力目录", "film.quality.confirmVersion": "确认 {cost} 并创建新版本", "film.quality.credits": "{credits} 算力", "film.quality.cost": "费用", "film.quality.generationHint": "将保存当前镜头版本，并按当前模型报价原子创建阶段父任务和单镜头子任务。", "film.quality.safeHint": "检查不自动修改制作数据。", "film.quality.restorable": "可恢复实体版本", "film.quality.restore": "恢复",
  "film.error.conflict": "修订冲突：{message}。请刷新后重新应用本地修改。", "film.error.pdfOcr": "PDF 未提取到文本，请先 OCR 后再导入。", "film.confirm.refreshDrafts": "存在未保存的原稿或时间线编辑。刷新时保留本地草稿，继续吗？", "film.confirm.leave": "存在未保存修改，确定离开吗？", "film.canvasMissing": "影视画布已不存在",
  "film.backCanvas": "返回画布", "film.modeRevision": "Film Production Mode · 修订 {revision}", "film.refresh": "刷新", "film.sections": "影片工作台分区", "film.loading": "正在加载影片制作数据…", "film.actionSucceeded": "{action}成功", "film.refreshedDrafts": "已刷新，未保存草稿保持不变", "film.projectionRefreshed": "影视主线已刷新到真实画布；用户节点和布局保持不变", "film.projectionCommitted": "已回写 {count} 项画布修改，并刷新受管节点版本",
  "film.action.import": "导入原稿", "film.action.parse": "解析原稿", "film.notice.imported": "原稿已导入，确定性拆解产物等待审核", "film.notice.parsed": "文件解析完成，拆解产物等待审核", "film.action.decompose": "AI 故事拆解", "film.notice.decomposeQueued": "AI 拆解任务已入队；完成后会生成待审候选", "film.action.applyDecomposition": "采用 AI 拆解候选", "film.notice.decompositionApplied": "候选已采用并保存为可追溯结构版本；现在可以审批拆解阶段", "film.action.restoreStructure": "恢复故事结构", "film.notice.structureRestored": "历史故事结构已恢复；恢复前的当前结构也已归档，可再次恢复", "film.action.script": "AI 分集剧本", "film.notice.scriptQueued": "分集剧本任务已入队；完成后会生成待审候选", "film.action.applyScript": "采用 AI 分集剧本", "film.notice.scriptApplied": "本集剧本候选已采用并保存旧结构版本；现在可以审批剧本阶段", "film.action.applyStyle": "应用风格模板", "film.notice.styleApplied": "已将“{title}”添加为项目风格资产", "film.action.copyTemplate": "复制影视模板", "film.action.createAsset": "创建资产", "film.action.saveAsset": "保存资产", "film.action.saveEpisode": "保存集", "film.action.saveShot": "保存镜头", "film.action.createDialogue": "创建对白", "film.action.saveDialogue": "保存对白", "film.action.deleteDialogue": "删除对白",
  "film.action.submitReview": "提交审核", "film.action.approveStage": "批准阶段", "film.action.rejectStage": "退回阶段", "film.notice.submittedReview": "产物已提交审核；这不代表生成完成", "film.action.startGeneration": "开始生成", "film.notice.generationQueued": "生成任务已入队，请以 GenerationJob 状态为准", "film.action.createWaiver": "创建阶段豁免", "film.notice.waiverCreated": "阶段豁免已审计记录；质量检查和交付清单会持续披露", "film.action.revokeWaiver": "撤销阶段豁免", "film.notice.waiverRevoked": "阶段豁免已撤销，依赖闸门立即恢复", "film.action.adoptCanvas": "采用画布候选", "film.notice.canvasAdopted": "候选媒体已采用并记录画布、任务、模型和媒体版本来源", "film.action.adoptDirector": "采用 Director 拍摄版本", "film.notice.directorAdopted": "Director 构图已验证并冻结为正式镜头媒体版本", "film.action.bindDirector": "绑定 Director 场景版本", "film.notice.directorBound": "Director 场景、机位和角色站位快照已冻结", "film.shotMedia": "镜头媒体", "film.action.saveTimeline": "保存时间线", "film.notice.timelineSaved": "时间线已保存", "film.action.validate": "质量检查", "film.action.applyRepair": "批准并应用修复", "film.action.restoreVersion": "恢复历史版本", "film.action.export": "请求导出", "film.notice.exportRequested": "导出请求已提交，请刷新查看异步状态", "film.action.cancelExport": "取消导出", "film.notice.exportCanceled": "导出取消请求已提交", "film.action.agentValidate": "Agent 质量检查",
  "film.styles.title": "原创影视风格参考库", "film.styles.label": "原创影视风格参考模板", "film.styles.description": "模板由 OpenBoard 独立设计。应用后会创建项目内的风格资产，后续镜头继续使用现有资产绑定、版本和任务链路。", "film.styles.palette": "{title} 色板", "film.styles.applyLabel": "应用 {title} 到当前项目", "film.styles.apply": "应用到当前项目", "film.styles.copyLabel": "复制 {title} 为影视项目", "film.styles.copy": "复制为影视项目",
  "film.episodes.views.storyboard": "故事板", "film.timeline.title": "可视化剪辑台", "film.voice.identity": "声音身份",
} as const;

export const filmEnUS: Record<keyof typeof filmZhCN, string> = {
  "film.nav.manuscript": "Manuscript", "film.nav.decomposition": "AI breakdown", "film.nav.script": "AI screenplay", "film.nav.styles": "Style templates", "film.nav.assets": "Assets", "film.nav.episodes": "Episode production", "film.nav.tasks": "Tasks", "film.nav.projection": "Projection", "film.nav.timeline": "Timeline", "film.nav.quality": "Quality", "film.nav.delivery": "Delivery", "film.nav.agent": "Agent",
  "film.quality.title": "Quality check", "film.quality.run": "Run checks", "film.quality.summary": "{issues} issues and {repairs} repair proposals", "film.quality.impact": "Affects {targets} items · about {generations} generations", "film.quality.applied": "Applied", "film.quality.configureApprove": "Configure and approve", "film.quality.approveApply": "Approve and apply", "film.quality.repairModel": "Repair generation model", "film.quality.noModel": "No model supports this repair stage", "film.quality.loadingCatalog": "Loading capability catalog", "film.quality.confirmVersion": "Confirm {cost} and create a new version", "film.quality.credits": "{credits} credits", "film.quality.cost": "cost", "film.quality.generationHint": "The current shot version will be saved, then a stage parent job and per-shot child job will be created atomically using the current quote.", "film.quality.safeHint": "Checks never modify production data automatically.", "film.quality.restorable": "Restorable entity versions", "film.quality.restore": "Restore",
  "film.error.conflict": "Revision conflict: {message}. Refresh before applying local changes again.", "film.error.pdfOcr": "No text could be extracted from the PDF. Run OCR before importing it.", "film.confirm.refreshDrafts": "There are unsaved manuscript or timeline edits. Keep local drafts while refreshing?", "film.confirm.leave": "There are unsaved changes. Leave anyway?", "film.canvasMissing": "The film canvas no longer exists",
  "film.backCanvas": "Back to canvas", "film.modeRevision": "Film Production Mode · revision {revision}", "film.refresh": "Refresh", "film.sections": "Film workbench sections", "film.loading": "Loading film production data…", "film.actionSucceeded": "{action} succeeded", "film.refreshedDrafts": "Refreshed; unsaved drafts were preserved", "film.projectionRefreshed": "The production line was projected to the real canvas; user nodes and layout were preserved", "film.projectionCommitted": "Committed {count} canvas changes and refreshed managed-node versions",
  "film.action.import": "Import manuscript", "film.action.parse": "Parse manuscript", "film.notice.imported": "Manuscript imported; deterministic breakdown is awaiting review", "film.notice.parsed": "File parsed; breakdown is awaiting review", "film.action.decompose": "AI story breakdown", "film.notice.decomposeQueued": "AI breakdown queued; a review candidate will be created when it completes", "film.action.applyDecomposition": "Apply AI breakdown candidate", "film.notice.decompositionApplied": "Candidate applied as a traceable structure version; the breakdown stage can now be approved", "film.action.restoreStructure": "Restore story structure", "film.notice.structureRestored": "Historical story structure restored; the previous current structure was also archived", "film.action.script": "AI episode screenplay", "film.notice.scriptQueued": "Episode screenplay queued; a review candidate will be created when it completes", "film.action.applyScript": "Apply AI episode screenplay", "film.notice.scriptApplied": "Episode screenplay candidate applied and the prior structure archived; the screenplay stage can now be approved", "film.action.applyStyle": "Apply style template", "film.notice.styleApplied": "Added “{title}” as a project style asset", "film.action.copyTemplate": "Copy film template", "film.action.createAsset": "Create asset", "film.action.saveAsset": "Save asset", "film.action.saveEpisode": "Save episode", "film.action.saveShot": "Save shot", "film.action.createDialogue": "Create dialogue", "film.action.saveDialogue": "Save dialogue", "film.action.deleteDialogue": "Delete dialogue",
  "film.action.submitReview": "Submit for review", "film.action.approveStage": "Approve stage", "film.action.rejectStage": "Reject stage", "film.notice.submittedReview": "Outputs submitted for review; this does not mean generation has completed", "film.action.startGeneration": "Start generation", "film.notice.generationQueued": "Generation queued; use GenerationJob status as the source of truth", "film.action.createWaiver": "Create stage waiver", "film.notice.waiverCreated": "Stage waiver recorded in the audit trail; quality checks and delivery manifests continue to disclose it", "film.action.revokeWaiver": "Revoke stage waiver", "film.notice.waiverRevoked": "Stage waiver revoked and dependency gates restored immediately", "film.action.adoptCanvas": "Adopt canvas candidate", "film.notice.canvasAdopted": "Candidate media adopted with canvas, job, model, and media-version lineage", "film.action.adoptDirector": "Adopt Director capture", "film.notice.directorAdopted": "Director composition validated and frozen as an official shot media version", "film.action.bindDirector": "Bind Director scene version", "film.notice.directorBound": "Director scene, camera, and character-position snapshots frozen", "film.shotMedia": "shot media", "film.action.saveTimeline": "Save timeline", "film.notice.timelineSaved": "Timeline saved", "film.action.validate": "Quality check", "film.action.applyRepair": "Approve and apply repair", "film.action.restoreVersion": "Restore historical version", "film.action.export": "Request export", "film.notice.exportRequested": "Export requested; refresh to see asynchronous status", "film.action.cancelExport": "Cancel export", "film.notice.exportCanceled": "Export cancellation requested", "film.action.agentValidate": "Agent quality check",
  "film.styles.title": "Original film style reference library", "film.styles.label": "Original film style reference templates", "film.styles.description": "Templates are independently designed by OpenBoard. Applying one creates a project style asset while subsequent shots continue using existing asset bindings, versions, and job lineage.", "film.styles.palette": "{title} palette", "film.styles.applyLabel": "Apply {title} to this project", "film.styles.apply": "Apply to project", "film.styles.copyLabel": "Copy {title} as a film project", "film.styles.copy": "Copy as film project",
  "film.episodes.views.storyboard": "Storyboard", "film.timeline.title": "Visual timeline editor", "film.voice.identity": "Voice identity",
};
